name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Configuration: Release
    steps:
    - uses: actions/checkout@v4
    - name: install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: build
      run: dotnet build -bl:bin/build.binlog
    - name: test
      run: dotnet test --no-build --verbosity normal
